title: hamitabis
description: >- 
  Security and Low-level Enthusiast
url: https://hamitabis.github.io/

paginate: 5

dash:
  avatar_source: github
  github_username: hamitabis

remote_theme: bitbrain/jekyll-dash
plugins:
  - jekyll-feed
  - jekyll-remote-theme
